remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have on

show_downloads: false
google_analytics: [Your Google Analytics tracking ID]

title: Raghunath Reddy
description: "Technical Content Writer, Editor, and Product Marketer"

plugins:
  - jekyll-paginate

paginate: 5 # number of posts per page
# paginate_path: "/page:num/" # path for the paginated pages
