remote_theme: pages-themes/minima
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-paginate
paginate: 5

title: Raghunath Reddy
description: Content Editor, Technical Content Writer, Product Marketer
